= solarized module

The `solarized` module contains the following:

* <<style>>
** `solarized:directive()`
* <<color>>
** `solarized:color()`
* <<styled>>
** `solarized:styled/1`
* <<simple>>
** `solarized:Color/1`
** `solarized:Color/2`
** `solarized:Color/3`
* <<titles>>
** `solarized:title/2`
** `solarized:section/2`
* <<term>>
** `solarized:term/2`
** `solarized:term/3`
* <<diff>>
** `solarized:diff/4`
** `solarized:term/5`
* <<utilities>>
** <<columns>>
** <<rows>>
** <<nl>>

[#style]
== Style directives

A style is made up of five components:

* it's `color()` (<<color>>),
* a `bold` toggle,
* a `highlight` toggle,
* a `reverse` toggle,
* and an `underline` toggle.

A style can have any of it's five components changed with the following
directives:

[source,erlang]
----
-type solarized:directive() ::
    color() |
    bold | bold_off |
    highlight | highlight_off |
    reverse | reverse_off |
    underline | underline_off.
----

Multiple directives can be applied at once
(i.e. `red` and `bold`)
as a single application.

[source,erlang]
----
-type solarized:application() ::
    directive() |
    {directive(), directive()}.
----

NOTE: This is currently limited to applying a pair of directives and covers
most use cases. This may be expanded to larger tuples in the future.

[#color]
== Colors

A style's color can be one of:

[source,erlang]
----
-type solarized:color() ::
    text |
    comment |
    emphasize |
    blue |
    cyan |
    green |
    magenta |
    orange |
    red |
    violet |
    yellow.
----

[#styled]
== Styled output

Styled text can be output to the console with:

[source,erlang]
----
-spec solarized:styled(Text) -> ok
    when
      Text :: solarized:styled().
----

where `solarized:styled()` is an extension of `unicode:chardata()` that
contains directives applied to text in the form:

[source,erlang]
----
-type solarized:applied() ::
    {Apply :: directive(), Text :: styled()} |
    {Apply1 :: directive(), Apply2 :: directive(), Text :: styled()}.
----

and is fully defined as:

[source,erlang]
----
-type solarized:styled() ::
    unicode_binary() |
    applied() |
    maybe_improper_list(unicode_char() | styled(),
                        unicode_binary() | applied() | []).
-type unicode_char() :: char().
-type unicode_binary() :: unicode:unicode_binary().
----

[#simple]
== Simple output

When output is of only one style it can be output with shortcuts named for
each of the colors.
These shortcuts have an interface similar to `io:put_chars/1` and `io:format/2`.

[source,erlang]
----
-spec solarized:Color(Text) -> ok
    when
      Color :: solarized:color(),
      Text :: unicode:chardata().

Color(Text) ->
    styled({Color, Text}).

-spec solarized:Color(Format, Data) -> ok
    when
      Color :: solarized:color(),
      Format :: io:format(),
      Data :: [term()].

Color(Format, Data) ->
    styled({Color, io_lib:format(Format, Data)}).

-spec solarized:Color(Apply, Text) -> ok
    when
      Color :: solarized:color(),
      Apply :: solarized:directive(),
      Text :: unicode:chardata().

Color(Apply, Text) ->
    styled({Color, Apply, Text}).

-spec solarized:Color(Apply, Format, Data) -> ok
    when
      Color :: solarized:color(),
      Apply :: solarized:directive(),
      Format :: io:format(),
      Data :: [term()].

Color(Apply, Format, Data) ->
    styled({Color, Apply, io_lib:format(Format, Data)}).
----

[#titles]
== Title and section headings

Output title and section headings in the form:

----
== Title =====================
-- Section -------------------
----

[source,erlang]
----
-spec solarized:title(Style, Text) -> ok
    when
      Style :: application(),
      Text :: unicode:chardata().

-spec solarized:section(Style, Text) -> ok
    when
      Style :: application(),
      Text :: unicode:chardata().
----

NOTE: `solarized:columns()` is used to adapt to different terminal widths.

Inspired by error messages of https://elm-lang.org/[Elm].

[#term]
== Term output

Output erlang terms formatted like Michael does:

[source,erlang]
----
-spec solarized:term(Style, Term) -> ok
    when
      Style :: application(),
      Term :: term().

-spec solarized:term(Style, Term, Options) -> ok
    when
      Style :: application(),
      Term :: term(),
      Options :: diff_options().
----

where the `Options` are shared with <<diff>>.

[#diff]
== Diff output

Diff two erlang terms producing `styled()` text:

[source,erlang]
----
-spec solarized:diff(OldStyle, NewStyle, OldTerm, NewTerm) -> ok
    when
      OldStyle :: application(),
      NewStyle :: application(),
      OldTerm :: term(),
      NewTerm :: term().

-spec solarized:diff(OldStyle, NewStyle, OldTerm, NewTerm, Options) -> ok
    when
      OldStyle :: application(),
      NewStyle :: application(),
      OldTerm :: term(),
      NewTerm :: term(),
      Options :: diff_options().

-type solarized_diff:options() ::
    #{ indent => pos_integer() | styled(),
       hanging => boolean(),
       common => application()
       width => pos_integer()}.
----

with `Options`:

indent::
Either the number of spaces to indent or some styled text.

hanging::
For multi-line text and a styled indent:
+
  * *false*: all lines are indented the same, or
  * *true*: (*default*) following lines are indented with spaces equal in width to the first line styled indent.

common::
The applied style for term components that are the same.

width::
Maximum with of formatted term not including size of indent.
The width is clamped by the terminal width (<<columns>>).

[#utilities]
== Utilities

[#columns]
=== `solarized:columns()`

[source,erlang]
----
-spec solarized:columns() -> Columns
    when
      Columns :: pos_integer().
----

This is a wrapper around `io:columns()` that returns a default of `80` when
the underlying call is unsupported.

[#rows]
=== `solarized:rows()`

[source,erlang]
----
-spec solarized:rows() -> Rows
    when
      Rows :: pos_integer().
----

This is a wrapper around `io:rows()` that returns a default of `25` when
the underlying call is unsupported.

[#nl]
=== `solarized:nl()`

[source,erlang]
----
-spec solarized:nl() -> ok.
----

This is an alias for `io:nl()`.

